name: 'GitHub Actions DZqiandao Bot'
# UTC17:00(北京UTC+8 01:00点)触发任务
on:
  workflow_dispatch:
  push:
  schedule:
    - cron: '0 16 * * *'

jobs:
  curl-discuz-A:
     runs-on: ubuntu-latest
     steps:
       - name: 'xecute command'
         env:
          USER_AGENT: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36'
          COOKIE: ${{ secrets.COOKIE_B }}
          #DZ论坛的防攻击机制验证码
          FORMHASH: ${{ secrets.FORMHASH_B }}
         # 向站点发送 GET 请求
         run:                                 
          curl -X POST -A "$USER_AGENT" -b "$COOKIE" -F "formhash=$FORMHASH" -F "qdxq=nu" -F "admode=2" -F "todaysay=" -F "fastreply=0" "https://www.3swg.com/plugin.php?id=dsu_paulsign:sing&operation=qiandao&infloat=1&sign_as=1&inajax=1"
          
  curl-discuz-B:
     runs-on: ubuntu-latest
     steps:
       - name: 'xecute command'
         env:
          USER_AGENT: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36'
          COOKIE: ${{ secrets.COOKIE_A }}
          #DZ论坛的防攻击机制验证码
          FORMHASH: ${{ secrets.FORMHASH_A }}
         # 向站点发送 GET 请求
         run:                                 
          curl -X POST -A "$USER_AGENT" -b "$COOKIE"  -F "formhash=$FORMHASH" -F "qdxq=nu" -F "admode=2" -F "todaysay=" -F "fastreply=0" "https://www.3swg.com/plugin.php?id=dsu_paulsign:sing&operation=qiandao&infloat=1&sign_as=1&inajax=1"
