name: 'GitHub Actions DZqiandao Bot'
# UTC17:00(北京UTC+8 01:00点)触发任务
on:
  workflow_dispatch:
  push:
  schedule:
    - cron: '0 16 * * *'

jobs:
  curl-discuz:
     runs-on: ubuntu-latest
     steps:
       - name: 'xecute command'
         env:
          USER_AGENT: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36'
          COOKIE: ${{ secrets.COOKIE }}
          #DZ论坛的防攻击机制验证码
          FORMHASH: ${{ secrets.FORMHASH }}
         # 向站点发送 GET 请求
         run:                                 
          curl -A "$USER_AGENT" -b "$COOKIE" "https://www.3swg.com/k_misign-sign.html?operation=qiandao&format=button&formhash=$FORMHASH&inajax=1&ajaxtarget=midaben_sign"
